### ISSUE TITLE
send button should not appear if no prescription is selected on the right

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#34]
#33 is now working. 

But: the "Senden" button now appears, even if there is not prescription selected on the right. So if the user clicks the buttons "Senden", nothing happens if he has not clicked "Speichern" first.

The button "Senden" should only be clickable if a prescription is selected on the right, meaning once the User has clicked "Speichern".

And once the "Speichern" Button has been clicked, it should not be clickable anymore unless the User modified something in the prescription, i.e. updated the prescription text, added a drug, changed a patient or deleted a drug.

**Comment by b123400** [comment]
> The button "Senden" should only be clickable if a prescription is selected on the right, meaning once the User has clicked "Speichern".

There is [some logic](https://github.com/zdavatz/amiko-osx/blob/bb9ad286c7b486f45b10ec3915c66bbef2d1e41b/AmiKoOSX/MLMainWindowController.m#L1494) that tries to save the prescription, when the send button is pressed and the prescription is not saved. However, that code doesn't work and therefore the send button does nothing.

I think we should fix the bug instead of disabling the button.

**Comment by zdavatz** [comment]
I agree!
